version: '3.8'

services:
  jupyterlab:
    build: .
    container_name: jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    depends_on:
      - postgres
      - mlflow

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mlops_db
    ports:
      - "5432:5432"

  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow
    ports:
      - "5000:5000"
    environment:
      BACKEND_STORE_URI: postgresql://user:password@postgres/mlops_db
    command: >
      /bin/sh -c "pip install psycopg2-binary &&
      mlflow server --backend-store-uri postgresql://user:password@postgres/mlops_db --default-artifact-root /mlflow --host 0.0.0.0"
