version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.10.0
    container_name: mlflow_server
    ports:
      - "5000:5000"
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      MLFLOW_ARTIFACT_ROOT: "/mlflow-artifacts"
    volumes:
      - mlflow-data:/mlflow-artifacts
    env_file: .env

  api:
    build: .
    container_name: mlflow_api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
    depends_on:
      - mlflow
    env_file: .env

volumes:
  mlflow-data:
